version: '3'
services:
  web:
    environment:
      - CHOKIDAR_USEPOLLING=true # for windows auto reload
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules #do not map node modules folder in container to pc 
      - .:/app # map everything else
  tests:
    environment:
      - CHOKIDAR_USEPOLLING=true # for windows auto reload
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules #do not map node modules folder in container to pc 
      - .:/app # map everything else
    command: ["npm", "run", "test"]
